name: Test mp

on:
  repository_dispatch:
    types: [ mp-push, mp-pull_request ]

# Declare default permissions as readonly.
permissions: read-all

env:
  repository: 'voicemeet/frontend-mp'
  main-path: 'main'
  source-path: 'mp'

jobs:
  mp:
    name: Create mp
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
        with:
          path: ${{ env.main-path }}

      - uses: actions/checkout@v6
        with:
          repository: ${{ env.repository }}
          ref: ${{ github.event.client_payload.sha }}
          token: ${{ secrets.VM_RELEASE_TOKEN }}
          path: ${{ env.source-path }}

      - name: Set node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
          package-manager-cache: false

      - name: Install deps
        run: |
          npm i -g corepack
          corepack enable
          pnpm install
        working-directory: ${{ env.source-path }}

      - name: Build
        run: pnpm build:h5
        working-directory: ${{ env.source-path }}

      - name: Copy index.html to 404.html
        run: cp ./dist/build/h5/index.html ./dist/build/h5/404.html
        working-directory: ${{ env.source-path }}

      - uses: actions/upload-artifact@v5
        with:
          name: mp-artifact
          path: ./${{ env.source-path }}/dist/build/h5
